Pdsf csv input
akafael/ufpe-project-bsg pull request #44
Opened 2023-09-09 19:54 UTC by pdsfilho

Code for showing outcome of CSV reading with field identification.

2023-09-10 20:39 UTC, akafael commented
Suggestion:
 * [ ] Rename `CSV_write` files to `csvutils`
 * [ ] Add read functions 
```
void readCSV(VehicleData* csvdata, int numEntries, const char* filename);
void readCSVLine(VehicleData data, char* csvLine);
```
 * [ ] Move functions from `car.h` and `car.c` to `csvutils`
 * [ ] Remove car files

2023-09-11 00:38 UTC, akafael requested changes

2023-09-11 00:38 UTC, akafael commented on code/test_csvutils.c
> +  char* expectedCsvLine = "1,2,3,4,5,6,0,8,9,10,11\n";
```suggestion
  char* expectedCsvLine = "1,2,3,1,5,6,0,8,9,10\n";
```

2023-09-11 00:47 UTC, akafael requested changes

2023-09-11 00:47 UTC, akafael commented on code/test_csvutils.c
> +  char* expectedCsvLine = "1,2,3,4,5,6,0,8,9,10,11,12,13\n";
```suggestion
  char* expectedCsvLine = "1,2,3,4,5,6,0,8,9,10,11,12,13";
```

2023-09-11 00:58 UTC, pdsfilho commented on code/test_csvutils.c
> +  char* expectedCsvLine = "1,2,3,4,5,6,0,8,9,10,11,12,13\n";
solved, thanks!

2023-09-11 01:28 UTC, akafael approved these changes

2023-09-11 01:28 UTC, merged